scripts/calcurse-upgrade: Add a "--config" option
This allows for specifying an alternate configuration file which is
useful if you use a non-default data directory.

Signed-off-by: Lukas Fleischer <calcurse@cryptocrack.de>

diff --git a/scripts/calcurse-upgrade b/scripts/calcurse-upgrade
--- a/scripts/calcurse-upgrade
+++ b/scripts/calcurse-upgrade
@@ -2,7 +2,16 @@
 
 set -e
 
-CONFFILE=$HOME/.calcurse/conf
+if [ "$1" = "--config" ]; then
+  CONFFILE=$2
+else
+  CONFFILE=$HOME/.calcurse/conf
+fi
+
+if [ ! -e "$CONFFILE" ]; then
+  echo "Configuration file not found: $CONFFILE" >&2
+  exit 1
+fi
 
 if grep -q -e '^auto_save=' -e '^auto_gc=' -e '^periodic_save=' \
   -e '^confirm_quit=' -e '^confirm_delete=' -e '^skip_system_dialogs=' \
